name: Build and publish edge image

on:
    push:
        branches: [main]
    workflow_dispatch: {}

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}

env:
    REGISTRY: ghcr.io

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    dockerize-edge:
        # only run edge build on non-tag pushes (e.g. branch pushes to main)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository_owner }}/tailscale-derp
                  tags: |
                      type=edge

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push docker image (edge)
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64,linux/arm64
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
